package util;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import util.StringUtils;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jadson' at '02/04/16 21:07' with Gradle 2.10
 *
 * @author jadson, @date 02/04/16 21:07
 */
public class StringUtilsTest {
    
	@Test 
    public void testEmptyString() {
        assertTrue(StringUtils.isEmpty(""));
    }
}
