package util;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jadson' at '02/04/16 21:07' with Gradle 2.10
 *
 * @author jadson, @date 02/04/16 21:07
 */
public class StringUtils {
	
    public static boolean isEmpty(String s) {
        return s == null || s.trim().equals("");
    }
}
