import test.StringUtils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return StringUtils.isEmpty("teste");
    }
}
