package test;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class StringUtils {
	
	public static boolean isEmpty(String s) {
		return s == null || s.trim().equals("");
	}
}
