/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import test.StringUtils;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        StringUtils classUnderTest = new StringUtils();
       
    }
}
